### ISSUE TITLE
云编译插件问题

### ISSUE THREAD

**Issue by serafwind** [Ljzkirito/Actions-Padavan_Redmi-AC2100#1]
你好，你这个.yml文件好像无法通过直接修改里面的y or n 来达到选择集成对应的插件功能

**Comment by serafwind** [comment]
发错仓库了··不好意思···是hank的

**Comment by serafwind** [comment]
对了 用你的仓库编译的时候 会报错，好像是old token的问题

**Comment by Ljzkirito** [comment]
我看了一下，可能是GitHub偶发错误，只要设置了有关`secrets.ACTIONS_REPO_PAT`就行，参阅[源码更新自动编译内容](https://p3terx.com/archives/build-openwrt-with-github-actions.html#toc_13)
