### ISSUE TITLE
no GITHUB_TOKEN found. pass `GITHUB_TOKEN` as env

### ISSUE THREAD

**Issue by huawuhen** [Ljzkirito/Actions-Padavan_Redmi-AC2100#2]
编译出错提示 no GITHUB_TOKEN found. pass `GITHUB_TOKEN` as env 。

**Comment by Ljzkirito** [comment]
我这里编译是正常的，估计是Github抽风。也可参考以下步骤：
1.创建[Personal access token(PAT)](https://github.com/settings/tokens/new)，Expiration选择No expiration，勾选repo权限
2.然后点击自己仓库的Settings选项卡，再点击Secrets。添加名为GITHUB_TOKEN的加密环境变量，保存刚刚创建的 PAT 。
